apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "hello-world.fullname" . }}
data:
  {{- range $path, $bytes := .Files.Glob "secret/*" }}
  {{ base $path }}: {{ $.Files.Get $path | b64enc }}
  {{- end }}
  {{- $fullname := include "hello-world.fullname" . -}}
  {{- if .Values.mongoDb }}
    {{- $dbPassword := required "Please specify a MongoDB password" .Values.mongoDb.password }}
  db-uri: {{ printf "mongodb://admin:%s@%s-mongodb:27119/?authSource=admin" $dbPassword $fullname | b64enc | quote }}
  {{- end}}